# Generated by Django 4.1.5 on 2024-02-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visitors", "0005_visitorlog_status_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="max_uses",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="visitor",
            name="uses_remaining",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
